### ISSUE TITLE
Integrate YAML scenario actions

### ISSUE THREAD

**Issue by ohader** [TYPO3/testing-framework#155]
PoC

```
        versionVariants:
            - version: {title: 'EN: Welcome to ACME Inc', workspace: 1, slug: '/welcome-modified'}
              actions:
                - {action: 'move', type: 'afterRecord', target: 234, immediate: true}
                - {action: 'move', type: 'toPage', target: 123}
                - {action: 'move', type: 'toTop'}
                - {action: 'delete'}
                - {action: 'discard'}
```

* `immediate (boolean` whether to execute action immediately or deferred (once children are processed)
